- name: Leave Swarm
  docker_swarm:
    state: absent
    force: true

- name: Initialise Docker Swarm
  docker_swarm:
    state: present

- name: Inspect Swarm
  docker_swarm:
    state: inspect
  register: swarm_info

- name: Inspect Swarm Nodes
  docker_swarm_info:
    nodes: yes

- name: Export Variable
  add_host:
    name: "join_token"
    value: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
